services:
  auth-db:
    image: postgres:17-alpine
    container_name: auth-db
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authadmin
      POSTGRES_PASSWORD: 123
    ports:
      - "5434:5432"
    volumes:
      - auth-db-data:/var/lib/postgresql/data

volumes:
  auth-db-data:
